name: one_cask
description: "A new Flutter project."


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.6

  # Flutter Bloc for state management
  flutter_bloc: ^8.1.4

  # Bloc for state management
  bloc: ^8.1.3

  # For functional programming
  dartz: ^0.10.1

  # For resource locator
  get_it: ^7.6.7

  # For spacing
  gap: ^3.0.1

  # For SVGs
  flutter_svg: ^2.0.7

  # For connectivity
  internet_connection_checker: ^1.0.0+1

  # Dear google fonts
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
